[package]
name = "waifud"
version = "0.1.0"
authors = [ "Christine Dodrill <me@christine.website>" ]
edition = "2018"
build = "src/build.rs"
repository = "https://github.com/Xe/waifud"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel_migrations = "1"
r2d2_redis = "0.14.0"
serde_json = "1"
tracing = "0.1"
tracing-futures = "0.2"
tracing-log = "0.1"
tracing-subscriber = "0.2"
uuid = "0.8"

[dependencies.diesel]
version = "1"
features = [ "sqlite", "r2d2", "chrono", "uuid" ]

[dependencies.rocket]
version = "0.5.0-rc.1"
features = [ "json", "uuid" ]

[dependencies.rocket_sync_db_pools]
version = "0.1.0-rc.1"
features = [ "diesel_sqlite_pool" ]

[dependencies.rusqlite]
version = "0.25.1"
features = [ "bundled", "uuid", "serde_json" ]

[dependencies.serde]
version = "1"
features = [ "derive" ]

[dependencies.tokio]
version = "1"
features = [ "full" ]

[build-dependencies]
ructe = { version = "0.13" }
