[package]
name = "waifud"
version = "0.1.0"
authors = [ "Christine Dodrill <me@christine.website>" ]
edition = "2018"
build = "src/build.rs"
repository = "https://github.com/Xe/waifud"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r2d2_redis = "0.14.0"
serde_json = "1"
uuid = "0.8"

[dependencies.rocket]
version = "0.5.0-rc.1"
features = [ "secrets", "json", "uuid" ]

[dependencies.rocket_sync_db_pools]
version = "0.1.0-rc.1"
features = [ "diesel_sqlite_pool" ]

[dependencies.serde]
version = "1"
features = [ "derive" ]

[dependencies.tokio]
version = "1"
features = [ "full" ]

[build-dependencies]
ructe = { version = "0.13" }
