name: waifuctl
version: 0.1.0-dev
summary: waifud control program
description: |
  waifuctl lets you control and manipulate vms on self-hosted
  cloud infrastructure based on waifud.
  
  This is supposed to be pronounced "waifu cuddle".

base: core20
confinement: devmode

parts:
  waifuctl:
    plugin: rust
    source: .

apps:
  waifuctl:
    command: bin/waifuctl
